### ISSUE TITLE
Scripts 404 on https://porkostomus.github.io/mecca/

### ISSUE THREAD

**Issue by runejuhl** [porkostomus/mecca#2]
FYI some of the scripts used on https://porkostomus.github.io/mecca/ return 404:

~~~
dev-main.js:3 GET https://porkostomus.github.io/cljs-out/dev/goog/base.js net::ERR_ABORTED 404
(anonymous) @ dev-main.js:3
dev-main.js:4 GET https://porkostomus.github.io/cljs-out/dev/goog/deps.js net::ERR_ABORTED 404
(anonymous) @ dev-main.js:4
dev-main.js:5 GET https://porkostomus.github.io/cljs-out/dev/cljs_deps.js net::ERR_ABORTED 404
(anonymous) @ dev-main.js:5
2(index):12 GET https://porkostomus.github.io/cljs-out/dev/goog/deps.js net::ERR_ABORTED 404
~~~

Thought you might want to know, since it was just posted on Reddit: https://www.reddit.com/r/Clojure/comments/cx6km7/chiptune_tracker_8bit_music_synthsequencer_in/

**Comment by porkostomus** [comment]
Thanks for letting me know! I actually think it's pretty funny that people are sharing this because it's still in such an early stage and hardly ready for prime time. But it's fixed now. Cheers!

**Comment by runejuhl** [comment]
Sorry to bug you again, but it seems that it's still broken:

~~~
GET https://porkostomus.github.io/cljs-out/dev/goog/base.js net::ERR_ABORTED 404
(anonymous) @ dev-main.js:3
GET https://porkostomus.github.io/cljs-out/dev/cljs_deps.js net::ERR_ABORTED 404
(anonymous) @ dev-main.js:5
GET https://porkostomus.github.io/cljs-out/dev/goog/deps.js net::ERR_ABORTED 404
(anonymous) @ dev-main.js:4
GET https://porkostomus.github.io/cljs-out/dev/cljs_deps.js net::ERR_ABORTED 404
~~~

**Comment by porkostomus** [comment]
Ah, thanks! Now I understand that I need to recompile the demo every time because it's using the same dev build.
